<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [2]:
import pandas as pd 
import plotly.graph_objects as go  
import numpy as np 
from lin_plots import * 


pd.set_option("display.max_rows",
              10000, 
              "display.max_columns", 
              10000)

In [3]:
## Read in the data
offense_stats = pd.read_csv('csv_files/game_predictions_offense.csv') 
defense_stats = pd.read_csv('csv_files/game_predictions_defense.csv') 
offense_defense_stats = pd.read_csv('csv_files/game_predictions_total.csv') 
offense_stats.head()

,Unnamed: 0,team,opponent,year,team_win,unnamed: 0,g,mp,fg,fg%,3p,3p%,ft,ft%,orb,drb,trb,ast,stl,blk,tov,pf,pts,playoffs,unnamed: 0.1,g.1,mp.1,fg.1,fg%.1,3p.1,3p%.1,ft.1,ft%.1,orb.1,drb.1,trb.1,ast.1,stl.1,blk.1,tov.1,pf.1,pts.1,playoffs.1
0,0,atlanta_hawks,boston_celtics,2000,2,24,82.0,241.8,36.6,0.441,3.1,0.317,18.0,0.743,14.0,31.3,45.3,18.9,6.1,5.6,15.4,21.0,94.3,0,8,82.0,240.6,37.2,0.444,5.1,0.331,19.8,0.745,13.5,29.5,43.0,21.2,9.7,3.5,15.4,27.1,99.3,0
1,1,atlanta_hawks,charlotte_hornets,2000,2,24,82.0,241.8,36.6,0.441,3.1,0.317,18.0,0.743,14.0,31.3,45.3,18.9,6.1,5.6,15.4,21.0,94.3,0,13,82.0,241.2,35.8,0.449,4.1,0.339,22.7,0.758,10.8,32.1,42.9,24.7,8.9,5.9,14.7,20.4,98.4,1
2,2,boston_celtics,charlotte_hornets,2000,2,8,82.0,240.6,37.2,0.444,5.1,0.331,19.8,0.745,13.5,29.5,43.0,21.2,9.7,3.5,15.4,27.1,99.3,0,13,82.0,241.2,35.8,0.449,4.1,0.339,22.7,0.758,10.8,32.1,42.9,24.7,8.9,5.9,14.7,20.4,98.4,1
3,3,atlanta_hawks,chicago_bulls,2000,0,24,82.0,241.8,36.6,0.441,3.1,0.317,18.0,0.743,14.0,31.3,45.3,18.9,6.1,5.6,15.4,21.0,94.3,0,28,82.0,241.5,31.3,0.415,4.1,0.329,18.1,0.709,12.6,28.3,40.9,20.1,7.9,4.7,19.0,23.3,84.8,0
4,4,boston_celtics,chicago_bulls,2000,1,8,82.0,240.6,37.2,0.444,5.1,0.331,19.8,0.745,13.5,29.5,43.0,21.2,9.7,3.5,15.4,27.1,99.3,0,28,82.0,241.5,31.3,0.415,4.1,0.329,18.1,0.709,12.6,28.3,40.9,20.1,7.9,4.7,19.0,23.3,84.8,0

In [4]:
offense_stats.team_win.value_counts()

2    2908
0    2871
1    2776
Name: team_win, dtype: int64

In [5]:
offense_stats.head()

,Unnamed: 0,team,opponent,year,team_win,unnamed: 0,g,mp,fg,fg%,3p,3p%,ft,ft%,orb,drb,trb,ast,stl,blk,tov,pf,pts,playoffs,unnamed: 0.1,g.1,mp.1,fg.1,fg%.1,3p.1,3p%.1,ft.1,ft%.1,orb.1,drb.1,trb.1,ast.1,stl.1,blk.1,tov.1,pf.1,pts.1,playoffs.1
0,0,atlanta_hawks,boston_celtics,2000,2,24,82.0,241.8,36.6,0.441,3.1,0.317,18.0,0.743,14.0,31.3,45.3,18.9,6.1,5.6,15.4,21.0,94.3,0,8,82.0,240.6,37.2,0.444,5.1,0.331,19.8,0.745,13.5,29.5,43.0,21.2,9.7,3.5,15.4,27.1,99.3,0
1,1,atlanta_hawks,charlotte_hornets,2000,2,24,82.0,241.8,36.6,0.441,3.1,0.317,18.0,0.743,14.0,31.3,45.3,18.9,6.1,5.6,15.4,21.0,94.3,0,13,82.0,241.2,35.8,0.449,4.1,0.339,22.7,0.758,10.8,32.1,42.9,24.7,8.9,5.9,14.7,20.4,98.4,1
2,2,boston_celtics,charlotte_hornets,2000,2,8,82.0,240.6,37.2,0.444,5.1,0.331,19.8,0.745,13.5,29.5,43.0,21.2,9.7,3.5,15.4,27.1,99.3,0,13,82.0,241.2,35.8,0.449,4.1,0.339,22.7,0.758,10.8,32.1,42.9,24.7,8.9,5.9,14.7,20.4,98.4,1
3,3,atlanta_hawks,chicago_bulls,2000,0,24,82.0,241.8,36.6,0.441,3.1,0.317,18.0,0.743,14.0,31.3,45.3,18.9,6.1,5.6,15.4,21.0,94.3,0,28,82.0,241.5,31.3,0.415,4.1,0.329,18.1,0.709,12.6,28.3,40.9,20.1,7.9,4.7,19.0,23.3,84.8,0
4,4,boston_celtics,chicago_bulls,2000,1,8,82.0,240.6,37.2,0.444,5.1,0.331,19.8,0.745,13.5,29.5,43.0,21.2,9.7,3.5,15.4,27.1,99.3,0,28,82.0,241.5,31.3,0.415,4.1,0.329,18.1,0.709,12.6,28.3,40.9,20.1,7.9,4.7,19.0,23.3,84.8,0

In [6]:
defense_stats.head()

,Unnamed: 0,team,opponent,year,team_win,unnamed: 0,g,mp,fg,fg%,3p,3p%,ft,ft%,orb,drb,trb,ast,stl,blk,tov,pf,pts,playoffs,unnamed: 0.1,g.1,mp.1,fg.1,fg%.1,3p.1,3p%.1,ft.1,ft%.1,orb.1,drb.1,trb.1,ast.1,stl.1,blk.1,tov.1,pf.1,pts.1,playoffs.1
0,0,atlanta_hawks,boston_celtics,2000,2,17,82.0,241.8,39.2,0.455,4.5,0.367,16.8,0.769,12.8,30.2,43.0,23.0,8.0,4.9,12.2,22.3,99.7,0,19,82.0,240.6,36.1,0.470,4.4,0.361,23.5,0.753,10.5,30.9,41.4,21.9,7.8,5.8,17.0,23.5,100.1,0
1,1,atlanta_hawks,charlotte_hornets,2000,2,17,82.0,241.8,39.2,0.455,4.5,0.367,16.8,0.769,12.8,30.2,43.0,23.0,8.0,4.9,12.2,22.3,99.7,0,9,82.0,241.2,37.2,0.448,5.0,0.378,16.4,0.745,11.8,31.1,42.9,23.2,7.4,5.1,15.8,25.3,95.8,1
2,2,boston_celtics,charlotte_hornets,2000,2,19,82.0,240.6,36.1,0.470,4.4,0.361,23.5,0.753,10.5,30.9,41.4,21.9,7.8,5.8,17.0,23.5,100.1,0,9,82.0,241.2,37.2,0.448,5.0,0.378,16.4,0.745,11.8,31.1,42.9,23.2,7.4,5.1,15.8,25.3,95.8,1
3,3,atlanta_hawks,chicago_bulls,2000,0,17,82.0,241.8,39.2,0.455,4.5,0.367,16.8,0.769,12.8,30.2,43.0,23.0,8.0,4.9,12.2,22.3,99.7,0,8,82.0,241.5,35.6,0.456,4.4,0.341,18.7,0.741,12.2,29.5,41.7,23.2,10.4,5.6,15.2,24.0,94.2,0
4,4,boston_celtics,chicago_bulls,2000,1,19,82.0,240.6,36.1,0.470,4.4,0.361,23.5,0.753,10.5,30.9,41.4,21.9,7.8,5.8,17.0,23.5,100.1,0,8,82.0,241.5,35.6,0.456,4.4,0.341,18.7,0.741,12.2,29.5,41.7,23.2,10.4,5.6,15.2,24.0,94.2,0

In [7]:
## Normalize the data- normalize by year, we don't need to normalize playoffs
from sklearn.preprocessing import MinMaxScaler

def Normalize(df): 
    
    ## Normalize By Year and then normalize overall
    
    df_group = df.drop(columns = ['team', 'opponent', 'team_win', 
                                  'playoffs', 'playoffs.1', 'unnamed: 0', 'unnamed: 0.1', 'g', 'g.1', 
                                 'mp', 'mp.1'])
    df_group = df_group.groupby(['year'])
    df_group = df_group.transform(lambda x: (x - x.mean())/(x.std())) 
    #df_group = df_group.drop(columns = ['level_0', 'index'])
    df_group[df_group.columns] = MinMaxScaler().fit_transform(df_group) 
    
    df = pd.concat(
        [df[['team','opponent', 'year', 'team_win']], df_group, df[['playoffs', 'playoffs.1']]], axis = 1
    )
    
    return df.loc[:, ~df.columns.str.match('Unnamed') ]


offense_stats_normal = Normalize(offense_stats) 
defense_stats_normal = Normalize(defense_stats) 
offense_stats_normal.head()

,team,opponent,year,team_win,fg,fg%,3p,3p%,ft,ft%,orb,drb,trb,ast,stl,blk,tov,pf,pts,fg.1,fg%.1,3p.1,3p%.1,ft.1,ft%.1,orb.1,drb.1,trb.1,ast.1,stl.1,blk.1,tov.1,pf.1,pts.1,playoffs,playoffs.1
0,atlanta_hawks,boston_celtics,2000,2,0.404185,0.352163,0.138065,0.260813,0.375532,0.514640,0.659632,0.532165,0.734343,0.204440,0.160732,0.487211,0.556587,0.258071,0.333888,0.560040,0.384880,0.401717,0.253015,0.534968,0.467704,0.620561,0.369784,0.523058,0.285076,0.600834,0.342313,0.494072,0.868795,0.608335,0,0
1,atlanta_hawks,charlotte_hornets,2000,2,0.404185,0.352163,0.138065,0.260813,0.375532,0.514640,0.659632,0.532165,0.734343,0.204440,0.160732,0.487211,0.556587,0.258071,0.333888,0.427149,0.451239,0.263849,0.310239,0.863893,0.540557,0.322730,0.715869,0.513422,0.569782,0.481451,0.666479,0.403221,0.124587,0.570576,0,1
2,boston_celtics,charlotte_hornets,2000,2,0.449942,0.385560,0.428049,0.346813,0.513892,0.525498,0.601418,0.309040,0.510725,0.369585,0.729092,0.225825,0.556587,0.721450,0.509619,0.427149,0.451239,0.263849,0.310239,0.863893,0.540557,0.322730,0.715869,0.513422,0.569782,0.481451,0.666479,0.403221,0.124587,0.570576,0,1
3,atlanta_hawks,chicago_bulls,2000,0,0.404185,0.352163,0.138065,0.260813,0.375532,0.514640,0.659632,0.532165,0.734343,0.204440,0.160732,0.487211,0.556587,0.258071,0.333888,0.000000,0.000000,0.263849,0.238708,0.342150,0.265957,0.521284,0.210053,0.320715,0.195597,0.332222,0.504396,0.961303,0.446707,0.000000,0,0
4,boston_celtics,chicago_bulls,2000,1,0.449942,0.385560,0.428049,0.346813,0.513892,0.525498,0.601418,0.309040,0.510725,0.369585,0.729092,0.225825,0.556587,0.721450,0.509619,0.000000,0.000000,0.263849,0.238708,0.342150,0.265957,0.521284,0.210053,0.320715,0.195597,0.332222,0.504396,0.961303,0.446707,0.000000,0,0

In [ ]:
## Perform Principal Component Analysis
from sklearn.decomposition import PCA 

pca = PCA().fit(offense_stats_normal.drop(columns = ['team', 'opponent', 'year', 'team_win'], axis = 1))  
(np.cumsum(pca.explained_variance_ratio_)) 

fig = go.Figure(go.Scatter(x = np.arange(0, pca.explained_variance_ratio_.shape[0], 1), 
                    y = np.cumsum(pca.explained_variance_ratio_)))
fig.show()